# Generated by Django 5.1.3 on 2024-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('edit_car', 'Can edit car'), ('view_car_details', 'Can view car details')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], help_text='Rol del usuario para determinar sus permisos.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(help_text='Modelo del auto.', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(help_text='Año de fabricación del auto.'),
        ),
    ]
